### ISSUE TITLE
Create (weekly?) scheduled tg25 archive crawl job that stores in existing repo

### ISSUE THREAD

**Issue by niccofyren** [gathering/tgno-frontend#40]

**Comment by niccofyren** [comment]
Experimented with a few different setups here when running crawl locally, and the simplest so far seems to be
1. mount a local version of `go-archive-tgno` directly on crawler container
2. once crawl is done, in `go-archive-tgno` add and commit all new files

```
  # Composer example (easily replicated via raw docker commands)
  crawler:
    image: webrecorder/browsertrix-crawler
    # Should match volumes being mounted
    command: crawl --config /app/configs/tgno.yaml
    volumes:
      - ./browsertrix-crawler/configs:/app/configs
      - /my-gathering-org-project-folder/go-archive-tgno/tgno:/crawls/collections/tgno
```

In a cron environment using a raw docker command is probably easier than composer setup, and startup script might be useful to automate repo management (replacing volume mounts). But steps should be the same
